api/views.py
from functools import wraps
from typing import NoReturn, Union

from bcrypt import hashpw, gensalt, checkpw
from flask import Blueprint, render_template, redirect, url_for, request, g, jsonify, session, current_app, \
    send_from_directory, abort
from flask_mail import Message
from itsdangerous import URLSafeTimedSerializer, SignatureExpired, BadSignature, BadTimeSignature
from qrcode import QRCode, constants
from rethinkdb import r

from api.extensions import mail

auth = Blueprint("auth", __name__, template_folder="templates", static_url_path="/static")


def login_required(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        if "student_id" not in session:
            return redirect(url_for("auth.login", next=request.url))
        return func(*args, **kwargs)

    return wrapper


def encode_data_to_file(data_to_encode: Union[dict, str], file_name: str) -> NoReturn:
    qr = QRCode(
        version=1,
        error_correction=constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    qr.add_data(data_to_encode)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    img.tobytes()
    img.save(file_name)


@auth.route("/", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        student_data = request.get_json()

        student_id = student_data["student_id"]
        password = student_data["password"]

        student = r.table("students").get(int(student_id)).run(g.con)

        if student is None:
            return jsonify({"error": "Student with that id was not found in the system"}), 404
        else:
            if "password" in student.keys():
                authenticated = checkpw(password.encode("utf-8"), student["password"])

                if authenticated:
                    result = r.table("students").get(int(student_id)).update({
                        "credit_points": r.row["credit_points"] + 10
                    }).run(g.con)

                    if result["replaced"] == 1:
                        session["student_id"] = student["id"]
                        student_doc_2 = r.table("students").get(int(student_id)).run(g.con)
                        student_doc = {
                            "id": student_doc_2["id"],
                            "expiry_date": student_doc_2["expiry_date"],
                            "status": student_doc_2["status"],
                            "credit_points": student_doc_2["credit_points"],
                        }
                        file_name = current_app.config["STUDENT_IMAGES"] + str(session["student_id"]) + ".png"
                        print(file_name)

                        encode_data_to_file(student_doc, file_name)
                        return jsonify({"data": "Login Successful. 10 Credit Points Awarded"}), 200
                    elif result["errors"] != 0:
                        session["student_id"] = student["id"]
                        student_doc_2 = r.table("students").get(int(student_id)).run(g.con)
                        student_doc = {
                            "id": student_doc_2["id"],
                            "expiry_date": student_doc_2["expiry_date"],
                            "status": student_doc_2["status"],
                            "credit_points": student_doc_2["credit_points"],
                        }
                        file_name = current_app.config["STUDENT_IMAGES"] + str(session["student_id"]) + ".png"

                        encode_data_to_file(student_doc, file_name)
                        return jsonify({"data": "Login Successful. 10 Credit Points Was not Awarded"}), 200
                    else:
                        session["student_id"] = student["id"]
                        student_doc_2 = r.table("students").get(int(student_id)).run(g.con)
                        student_doc = {
                            "id": student_doc_2["id"],
                            "expiry_date": student_doc_2["expiry_date"],
                            "status": student_doc_2["status"],
                            "credit_points": student_doc_2["credit_points"],
                        }
                        file_name = current_app.config["STUDENT_IMAGES"] + str(session["student_id"]) + ".png"

                        encode_data_to_file(student_doc, file_name)
                        return jsonify({"data": "Login Successful"}), 200
                else:
                    return jsonify({"error": "Invalid credentials"}), 401
            else:
                return jsonify({"error": "Password has not been set, please register before proceesing to login"}), 400
    else:
        return render_template("login.html")


@auth.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":

        student_data = request.get_json()

        student_id = student_data["student_id"]
        password = student_data["password"]

        student = r.table("students").get(int(student_id)).run(g.con)
        if student is None:
            return jsonify({"error": "Student with that id was not found in the system"}), 404
        else:
            if "password" in student.keys():
                return jsonify(
                    {"error": "Account already exists and password was already set. Redirecting to login..."}), 406
            else:
                encrypted_password = hashpw(password.encode("utf-8"), gensalt(14))

                result = r.table("students").get(int(student_id)).update({"password": encrypted_password}).run(g.con)

                if result["errors"] != 0:
                    return jsonify({"error": "Something happened. Could not save password"}), 400
                else:
                    return jsonify({"data": "Records saved successfully"}), 200

    else:
        return render_template("register.html")


@auth.route("/images/<image>")
def send_image(image):
    try:
        return send_from_directory(current_app.config['STUDENT_IMAGES'], image, as_attachment=True)
    except FileNotFoundError:
        abort(404)


@auth.route("/profile", methods=["GET"])
@login_required
def profile():
    if "student_id" in session:
        student = r.table("students").get(session["student_id"]).run(g.con)
        return render_template("profile.html", student=student, image_name=str(session["student_id"]) + ".png")
    return jsonify({"error": "Login required"})


def send_mail(subject, to, template):
    msg = Message(
        subject,
        recipients=[to],
        html=template,
        sender=current_app.config['MAIL_DEFAULT_SENDER']
    )
    mail.send(msg)


def send_password_reset_email(user_email):
    password_reset_serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])

    password_reset_url = url_for("auth.reset_with_token",
                                 token=password_reset_serializer.dumps(user_email, salt="password-reset-salt"),
                                 _external=True)

    html = render_template('email_password_reset.html', password_reset_url=password_reset_url)

    send_mail('Password Reset Requested', user_email, html)


@auth.route("/reset_password", methods=["GET", "POST"])
def reset():
    if request.method == "POST":
        email_address = request.form["email"]
        send_password_reset_email(email_address)
        emails = r.table("students").pluck("email").coerce_to("array").run(g.con)

        if not email_address in [doc["email"] for doc in emails]:
            return jsonify({"error": "Email address was not found in our system"}), 404
        else:
            send_password_reset_email(email_address)
            return jsonify({"data": "Please Check your email for a password reset link"}), 200
    else:
        return render_template("reset.html")


@auth.route('/reset/<token>', methods=["GET", "POST"])
def reset_with_token(token):
    try:
        password_reset_serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
        email = password_reset_serializer.loads(token, salt='password-reset-salt', max_age=10)
    except (SignatureExpired, BadTimeSignature, BadSignature):
        return jsonify(
            {"error": 'The password reset link is invalid or has expired. Please resend the link again'}), 400
        return redirect(url_for("auth.reset"))

    doc_result = r.table("students").filter({"email": email}).coerce_to("array").run(g.con)

    if doc_result:
        if request.method == "POST":
            password = request.form["password"]
            confirm_password = request.form["confirm_password"]

            if password != confirm_password or confirm_password != password:
                return jsonify({"error": "Passwords do not match"}), 406
            else:
                password = password.encode("utf-8")
                hashed_password = hashpw(password, gensalt(14))
                result = r.table("students").get(doc_result[0]["id"]).update({"password": hashed_password}).run(g.con)
                if result["errors"] != 0:
                    return jsonify({"error": "Password was not updated"}), 406
                elif result["replaced"] == 1:
                    # return jsonify({"data": "Password has been updated successfully"}), 200
                    return redirect(url_for("auth.login"))
        else:
            return render_template('reset_password_with_token.html', token=token)
    else:
        return jsonify({"error": "Email is invalid"}), 404


@auth.route("/logout")
@login_required
def logout():
    session.pop("student_id", None)
    return redirect(url_for("auth.login"))

api/templates/base.html
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock%}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/vendor/tailwind.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/vendor/toastr.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
<body>
<nav>
    {% block nav %}
    {% endblock %}
</nav>
<main>
    {% block body %}
    {% endblock %}
</main>

<footer>
    {% block footer %}
    {% endblock %}
</footer>
    <script src="{{ url_for('static', filename='js/vendor/jquery.js') }}"></script>
    <script src="{{ url_for('static', filename='js/vendor/toastr.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>
</html>

api/templates/email_password_reset.html
You requested that the password for your Vivo Id System account be reset.
Please click the link below to reset your password:

<p>
<a href="{{ password_reset_url }}">{{ password_reset_url }}</a>
</p>

<p>
--<br>
Questions? Comments? Email m.k.ndirangu@gmail.com.
</p>

api/templates/login.html
{% extends "base.html" %}
{% block title %}
    Vivo ID System
{% endblock %}

{% block nav %}
{% endblock %}

{% block body %}
    <div id="login_main" class="bg-grey-lighter h-screen font-sans" style="background-color: #F0FFF0">
        <div class="container mx-auto h-full flex flex-col justify-center items-center">
            <img src="/static/images/vivo_logo.png" alt="">
            <form class="lg:w-1/3" sm:w-48 name="login_form" method="POST" action="{{ url_for('auth.login') }}">
                <p class="error" style="color: red"></p>
<!--                <p class="error error&#45;&#45;hidden" style="color: red"></p>-->
                <p class="success success--hidden text-teal-400"></p>
                <h1 class="font-hairline mb-6 text-center">Login to The Student ID System</h1>
                <div class="border-teal p-8 border-t-12 bg-white mb-6 rounded-lg shadow-lg">
                    <div class="mb-4">
                        <label class="font-bold text-grey-darker block mb-2">Student Id</label>
                        <input id="student_id" type="number" class="block appearance-none w-full bg-white border border-grey-light hover:border-grey px-2 py-2 rounded shadow" name="student_id"  placeholder="Student Id. No.">
                    </div>
    
                    <div class="mb-4">
                        <label class="font-bold text-grey-darker block mb-2">Password</label>
                        <input id="password" type="password" class="block appearance-none w-full bg-white border border-grey-light hover:border-grey px-2 py-2 rounded shadow" name="password" placeholder="Your Password">
                    </div>
    
                    <div class="flex flex-col items-center justify-between w-full">
                        <button class="bg-teal-400 hover:bg-teal text-white font-bold py-2 px-4 rounded w-full">
                            Login
                        </button>
                        <a class="pt-1 no-underline inline-block align-baseline font-bold text-sm text-blue hover:text-blue-dark float-right" href="{{ url_for('auth.reset')}}">
                            Forgot Password?
                        </a>
                    </div>
                    
                </div>
                <div class="text-center">
                    <p class="text-grey-dark text-sm">Don't have an account? <a href="{{ url_for('auth.register')}}" class="no-underline text-blue font-bold">Create an Account</a>.</p>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

api/templates/profile.html
{% extends "base.html" %}
{% block title %}
    Vivo Id System
{% endblock %}

{% block nav %}
<nav class="flex items-center justify-between flex-wrap bg-teal-500 p-6">
  <div class="flex items-center flex-shrink-0 text-white mr-6">
      <div class="fill-current h-10 w-10 mr-2">
          <img src="/static/images/vivo_logo_white.png" alt="" width="250" height="250">
      </div>
  </div>
  <div class="block lg:hidden">
    <button class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white">
      <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>
  <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
    <div class="text-sm lg:flex-grow">
    </div>
    <div>
        <a href="{{ url_for('auth.logout')}}" class="inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0">Logout</a>
    </div>
  </div>
</nav>
{% endblock %}

{% block body %}

<div id="profile" class="bg-grey-lighter h-screen font-sans" style="background-color: #F5F5F5">
    <div class="container mx-auto h-full flex justify-center items-center">
        <div lg:w-1/3" sm:w-48>
            <h1>
                <span style="color: black; font-weight: bold">Student: </span><span style="color: black">{{ student.first_name }} {{ student.surname }}</span>
            </h1>
            <h1>
                <span style="color: black; font-weight: bold">Student ID: </span><span style="color: black">{{ student.id }}</span>
            </h1>
            <h1>
                <span style="color: black; font-weight: bold">Status: </span><span style="color: black">{{ student.status}}</span>
            </h1>
            <img src="{{ url_for('auth.send_image', image=image_name)}}">
        </div>
    </div>
</div>
{% endblock %}

{% block footer %}
{% endblock %}

api/templates/register.html
{% extends "base.html" %}
{% block title %}
    Vivo ID System
{% endblock %}

{% block nav %}
{% endblock %}

{% block body %}

<div id="registration_main" class="bg-grey-lighter h-screen font-sans" style="background-color: #F0FFF0">
    <div class="container mx-auto h-full flex flex-col justify-center items-center">
        <img src="/static/images/vivo_logo.png" alt="">
        <form class="lg:w-1/3 sm:w-48" name="registration_form" method="POST" action="{{ url_for('auth.register') }}">
            <p class="error error--hidden" style="color: red"></p>
            <p class="success success--hidden text-teal-400"></p>
            <h1 class="font-hairline mb-6 text-center">SignUp for The Student ID System</h1>
            <div class="border-teal p-8 border-t-12 bg-white mb-6 rounded-lg shadow-lg">
                <div class="mb-4">
                    <label class="font-bold text-grey-darker block mb-2">Student Id</label>
                    <input name="student_id" id="student_id" type="number" class="block appearance-none w-full bg-white border border-grey-light hover:border-grey px-2 py-2 rounded shadow" id="student_id"  placeholder="Student Id. No.">
                </div>

                <div class="mb-4">
                    <label class="font-bold text-grey-darker block mb-2">Password</label>
                    <input name="password" type="password" class="block appearance-none w-full bg-white border border-grey-light hover:border-grey px-2 py-2 rounded shadow" id="password" placeholder="Password">
                </div>

                <div class="mb-4">
                    <label class="font-bold text-grey-darker block mb-2">Confirm Password</label>
                    <input name="confirm_password" type="password" class="block appearance-none w-full bg-white border border-grey-light hover:border-grey px-2 py-2 rounded shadow" id="confirm_password" placeholder="Confirm Password">
                </div>

                <div class="flex flex-col items-center justify-between w-full">
                    <button class="bg-teal-400 hover:bg-teal text-white font-bold py-2 px-4 rounded w-full">
                        Signup
                    </button>
                    <a class="pt-1 no-underline inline-block align-baseline font-bold text-sm text-blue hover:text-blue-dark float-right" href="#">
                        Forgot Password?
                    </a>
                </div>
                
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block footer %}
{% endblock %}

api/templates/reset.html
{% extends "base.html" %}
{% block title %}
    Vivo Student ID System
{% endblock %}

{% block nav %}
{% endblock %}

{% block body %}
<div id="reset" class="bg-grey-lighter h-screen font-sans" style="background-color: #F0FFF0">
        <div class="container mx-auto h-full flex flex-col justify-center items-center">
            <img src="/static/images/vivo_logo.png" alt="">
            <form class="lg:w-1/3" sm:w-48 name="password_reset_form" method="POST" action="{{ url_for('auth.reset') }}">
                <h1 class="font-hairline mb-6 text-center">Reset Password for Vivo ID System</h1>
                <div class="border-teal p-8 border-t-12 bg-white mb-6 rounded-lg shadow-lg">
                    <div class="mb-4">
                        <label class="font-bold text-grey-darker block mb-2">Email Address</label>
                        <input id="email" type="email" class="block appearance-none w-full bg-white border border-grey-light hover:border-grey px-2 py-2 rounded shadow" name="email"  placeholder="Email Address">
                    </div>

                    <div class="flex flex-col items-center justify-between w-full">
                        <button class="bg-teal-400 hover:bg-teal text-white font-bold py-2 px-4 rounded w-full">
                            Reset
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

api/templates/reset_password_with_token.html
{% extends "base.html" %}
{% block title %}
    Vivo ID System
{% endblock %}

{% block nav %}
{% endblock %}

{% block body %}

<div id="reset_with_token" class="bg-grey-lighter h-screen font-sans" style="background-color: #F0FFF0">
    <div class="container mx-auto h-full flex flex-col justify-center items-center">
        <img src="/static/images/vivo_logo.png" alt="">
        <form class="lg:w-1/3 sm:w-48" name="reset_with_token_form" method="POST" action="{{ url_for('auth.reset_with_token', token=token) }}">
            <h1 class="font-hairline mb-6 text-center">Reset Password for Vivo ID System</h1>
            <div class="border-teal p-8 border-t-12 bg-white mb-6 rounded-lg shadow-lg">
<!--                <div class="mb-4">-->
<!--                    <label class="font-bold text-grey-darker block mb-2">P</label>-->
<!--                    <input id="student_id" name="student_id" type="number" class="block appearance-none w-full bg-white border border-grey-light hover:border-grey px-2 py-2 rounded shadow" placeholder="Student Id No.">-->
<!--                </div>-->

                <div class="mb-4">
                    <label class="font-bold text-grey-darker block mb-2">Password</label>
                    <input  id="password" name="password" type="password" class="block appearance-none w-full bg-white border border-grey-light hover:border-grey px-2 py-2 rounded shadow" placeholder="Password">
                </div>

                <div class="mb-4">
                    <label class="font-bold text-grey-darker block mb-2">Confirm Password</label>
                    <input id="confirm_password" name="confirm_password" type="password" class="block appearance-none w-full bg-white border border-grey-light hover:border-grey px-2 py-2 rounded shadow" placeholder="Confirm Password">
                </div>

                <div class="flex flex-col items-center justify-between w-full">
                    <button class="bg-teal-400 hover:bg-teal text-white font-bold py-2 px-4 rounded w-full">
                        Reset
                    </button>
                </div>

            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block footer %}
{% endblock %}